### ISSUE TITLE
incomplete ways

### ISSUE THREAD

**Issue by nrenner** [simonpoole/mapsplit#2] opened 2013-03-21 17:40 UTC
Some tiles contain ways without referenced nodes. This seems to be the case when they are part of a multipolygon relation, but do not have nodes inside the tile themselves. 

The "completeRelations" parameter is not set (defaults to false), so I would expect the relations to be incomplete, not the ways. And I read the [Wiki description](http://wiki.openstreetmap.org/wiki/Mapsplit#Options) this way too.

An example is tile [4308_2856](http://tools.geofabrik.de/map/?type=Geofabrik_Standard&lon=9.33502&lat=47.73564&zoom=13&grid=1). It contains the incomplete ways 29433456, 29433458 (inners of [62921](http://www.openstreetmap.org/browse/relation/62921)) and 77004276 (inner of [1174277](http://www.openstreetmap.org/browse/relation/1174277)).

**Comment by simonpoole** [comment] 2018-12-14 13:49
Blast from the past ... the issue is fixed in https://github.com/simonpoole/mapsplit/commit/b1dd2c0715edcc423351770637722edfe6a371b7

**Comment by simonpoole** [comment] 2018-12-14 15:06
https://github.com/simonpoole/mapsplit/commit/158a6071be2c6f73f057087ea3dca438f852da3f should fix this,. The issue was in general relation members be added to tiles even if completeRelations was not set (the members -do- need to be iterated over to determine the geometry/tiles affected for the relation itself). Any consumer of OSM data needs to be able to deal with incomplete relations to start with so this change should not cause any further issues.

**Comment by simonpoole** [comment] 2019-05-05 13:12
No further feedback

**Closed by simonpoole** 2019-05-05 13:12 UTC
